apiVersion: v1
kind: Service
metadata:
  name : result-service
  labels:
    app: result
spec:
  type: ClusterIP
  selector:
    app: result
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 4000