apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
  namespace: test
  labels:
    app: result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - name: result
        image: yassine123432/result:1.0
        ports:
        - containerPort: 4000