apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-deployment
  labels:
    app: vote 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote  
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - name: vote
        image: yassine123432/vote:1.0
        ports:
        - containerPort: 5000
        env:
        - name: OPTION_A
          valueFrom:
            configMapKeyRef:
              name: voting-app-config
              key: OPTION_A
        - name: OPTION_B
          valueFrom:
            configMapKeyRef:
              name: voting-app-config
              key: OPTION_B
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: voting-app-config
              key: REDIS_HOST 